apiVersion: v1
kind: Pod
metadata:
  name: gcs-pod
spec:
  containers:
    - name: my-container
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: gcs-volume
          mountPath: /mnt/gcs
  volumes:
    - name: gcs-volume
      persistentVolumeClaim:
        claimName: gcs-volume-claim