apiVersion: v1
kind: Pod
metadata:
  name: gcsfuse-test
  namespace: app-gcs-fuse
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  terminationGracePeriodSeconds: 60
  containers:
    - image: busybox
      name: busybox
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: gcsfuse-test
          mountPath: /data
          readOnly: true
  serviceAccountName: gcs-sa
  volumes:
    - name: gcsfuse-test
      csi:
        driver: gcsfuse.csi.storage.gke.io
        volumeAttributes:
          bucketName: data-bucket34
          mountOptions: "implicit-dirs"
